// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoCheckUpdate() {
  return window['go']['main']['App']['AutoCheckUpdate']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function DownloadAndInstallUpdate(arg1) {
  return window['go']['main']['App']['DownloadAndInstallUpdate'](arg1);
}

export function GetAutoUpdateEnabled() {
  return window['go']['main']['App']['GetAutoUpdateEnabled']();
}

export function GetUpdateConfig() {
  return window['go']['main']['App']['GetUpdateConfig']();
}

export function GetVersionInfo() {
  return window['go']['main']['App']['GetVersionInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ResetSkipVersion() {
  return window['go']['main']['App']['ResetSkipVersion']();
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function SetAutoUpdate(arg1) {
  return window['go']['main']['App']['SetAutoUpdate'](arg1);
}

export function SetUpdateConfig(arg1) {
  return window['go']['main']['App']['SetUpdateConfig'](arg1);
}

export function SkipVersion(arg1) {
  return window['go']['main']['App']['SkipVersion'](arg1);
}
