// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetVersionInfo():Promise<Record<string, string>>;

export function Greet(arg1:string):Promise<string>;
