// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AutoCheckUpdate():Promise<void>;

export function CheckForUpdate():Promise<main.UpdateStatus>;

export function DownloadAndInstallUpdate(arg1:string):Promise<void>;

export function GetAutoUpdateEnabled():Promise<boolean>;

export function GetUpdateConfig():Promise<main.UpdateConfig>;

export function GetVersionInfo():Promise<Record<string, string>>;

export function Greet(arg1:string):Promise<string>;

export function ResetSkipVersion():Promise<void>;

export function RestartApp():Promise<void>;

export function SetAutoUpdate(arg1:boolean):Promise<void>;

export function SetUpdateConfig(arg1:main.UpdateConfig):Promise<void>;

export function SkipVersion(arg1:string):Promise<void>;
